version: "3.9"
services:
  postgres:
    container_name: techradar-db
    image: techradarapi/techradar-db:${TAG:-latest}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
