version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tech_radar}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "54321:5432"
