version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tech_radar}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    networks:
      - radar
  techradar-api:
    container_name: techradar-api
    image: techradarapi/techradar-api:1.0.5
    command: [
      "bash -c 'touch /app.jar'"
    ]
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    networks:
      - radar

networks:
  radar:
    name: radar
    driver: bridge
