version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
