version: "3.9"
services:
  postgres:
    container_name: postgres-ci-cd
    image: techradarapi/techradar-db:${TAG}
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    build:
      context: .
      dockerfile_inline: |
        FROM postgres:$POSTGRES_VERSION
        EXPOSE 5432
        COPY sql/* /docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - radar
  techradar-api:
    container_name: test-ci-cd
    image: techradarapi/techradar-api:${TAG}
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:$OPENJDK_VERSION
        EXPOSE 8080
        COPY target/*.jar app.jar
        ENTRYPOINT ["java","-jar","app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    networks:
      - radar
networks:
  radar:
    name: radar
    driver: bridge
