db:
  url: jdbc:postgresql://postgres:5432/tech_radar
  username: postgres
  password: postgres
  show-sql: true
  hbm2ddl-auto: create
  dialect: org.hibernate.dialect.PostgreSQLDialect
  default-batch-fetch-size: 10
