db:
  url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tech_radar}
  username: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:postgres}
  show-sql: ${DB_SHOW_SQL:true}
  hbm2ddl-auto: ${DB_HB2DDL_AUTO:validate}
  dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  default-batch-fetch-size: ${DB_DEFAULT_BATCH_FETCH_SIZE:10}
token:
  secret-key: ${TOKEN_SECRET_KEY:7234753778214125442A472D4B6150645367566B59703273357638792F423F45}
  expired:
    access: ${TOKEN_EXPIRED_ACCESS:60000}    #1 * 60 * 1000
    refresh: ${TOKEN_EXPIRED_REFRESH:120000} #2 * 60 * 1000
spring:
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:/changelog/master.xml}
