db:
  url: jdbc:postgresql://localhost:5433/tech_radar
  username: postgres
  password: postgres
  show-sql: true
  hbm2ddl-auto: create
  dialect: org.hibernate.dialect.PostgreSQLDialect
  default-batch-fetch-size: 10
org:
  hibernate:
    envers:
      audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy