name: On pull request action

on:
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ vars.POSTGRES_VERSION }}
        env:
          POSTGRES_USER: '${{ secrets.POSTGRES_DB_USERNAME }}'
          POSTGRES_PASSWORD: '${{ secrets.POSTGRES_DB_PASSWORD }}'
          POSTGRES_DB: '${{ vars.POSTGRES_DB }}'
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ vars.JAVA_VERSION }}'
          distribution: 'oracle'
      - name: Run tests with Maven
        run: mvn -B clean test
  build:
    needs: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ vars.JAVA_VERSION }}'
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip package
